name: Build and Push Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compile Java projects
        run: |
          mvn clean install -f Data-Entry/pom.xml
          mvn clean install -f Authentication/pom.xml
          mvn clean install -f Analytics/pom.xml
          mvn clean install -f ShowData/pom.xml

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull MySQL image
        run: docker pull mysql

      - name: Pull MongoDB image
        run: docker pull mongo

      - name: Build and push data-entry
        run: |
          docker build -t ghassan/data-entry:latest ./Data-Entry
          docker push ghassan/data-entry:latest

      - name: Build and push auth-server
        run: |
          docker build -t ghassan/auth-server:latest ./Authentication
          docker push ghassan/auth-server:latest

      - name: Build and push analysis-server
        run: |
          docker build -t ghassan/analysis-server:latest ./Analytics
          docker push ghassan/analysis-server:latest

      - name: Build and push data-reader
        run: |
          docker build -t ghassan/data-reader:latest ./ShowData
          docker push ghassan/data-reader:latest
