FROM openjdk:17

WORKDIR /Authentication
COPY target/Authentication-0.0.1-SNAPSHOT.jar /Authentication/Authentication-0.0.1-SNAPSHOT.jar
EXPOSE 8081
CMD ["java", "-jar", "Authentication-0.0.1-SNAPSHOT.jar"]

